package com.simpz.bitcoder.model.po;

import java.util.Date;

public class PermissionCodePo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_code.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_code.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_code.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_code.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_code.last_update_name
     *
     * @mbggenerated
     */
    private String lastUpdateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_code.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_code.valid
     *
     * @mbggenerated
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_code.id
     *
     * @return the value of permission_code.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_code.id
     *
     * @param id the value for permission_code.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_code.code
     *
     * @return the value of permission_code.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_code.code
     *
     * @param code the value for permission_code.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_code.desc
     *
     * @return the value of permission_code.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_code.desc
     *
     * @param desc the value for permission_code.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_code.create_time
     *
     * @return the value of permission_code.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_code.create_time
     *
     * @param createTime the value for permission_code.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_code.last_update_name
     *
     * @return the value of permission_code.last_update_name
     *
     * @mbggenerated
     */
    public String getLastUpdateName() {
        return lastUpdateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_code.last_update_name
     *
     * @param lastUpdateName the value for permission_code.last_update_name
     *
     * @mbggenerated
     */
    public void setLastUpdateName(String lastUpdateName) {
        this.lastUpdateName = lastUpdateName == null ? null : lastUpdateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_code.last_update_time
     *
     * @return the value of permission_code.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_code.last_update_time
     *
     * @param lastUpdateTime the value for permission_code.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_code.valid
     *
     * @return the value of permission_code.valid
     *
     * @mbggenerated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_code.valid
     *
     * @param valid the value for permission_code.valid
     *
     * @mbggenerated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}